In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
dataset=pd.read_csv("CKD.csv")

In [3]:
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3,0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2,0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1,0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1,0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0,0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0,0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0,2,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3,0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0,0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0,0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [4]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [5]:
dataset=dataset.astype(int)

In [6]:
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2,76,3,0,148,57,3,137,4,12,...,0,0,0,0,0,0,1,1,0,1
1,3,76,2,0,148,22,0,137,4,10,...,1,0,0,0,0,0,1,0,0,1
2,4,76,1,0,99,23,0,138,4,12,...,1,0,0,0,0,0,1,0,0,1
3,5,76,1,0,148,16,0,138,3,8,...,1,0,0,0,0,0,1,0,1,1
4,5,50,0,0,148,25,0,137,4,11,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51,70,0,0,219,36,1,139,3,12,...,1,0,0,0,0,0,1,0,0,1
395,51,70,0,2,220,68,2,137,4,8,...,1,0,0,1,1,0,1,0,1,1
396,51,70,3,0,110,115,6,134,2,9,...,1,0,0,1,1,0,0,0,0,1
397,51,90,0,0,207,80,6,142,5,8,...,1,0,0,1,1,0,1,0,1,1
398,51,80,0,0,100,49,1,140,5,16,...,1,0,0,0,0,0,1,0,0,0

In [7]:
dataset["classification_yes"].value_counts()

classification_yes
1    249
0    150
Name: count, dtype: int64

In [8]:
independent=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', ]]

In [9]:
dependent=dataset[['classification_yes']]

In [10]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independent,dependent,test_size=1/3,random_state=0)

In [11]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [12]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import GridSearchCV
param_grid={'n_neighbors':["int",5],"algorithm":['auto','ball_tree','kd_tree','brute'],'weights':['uniform','distance'],'leaf_size':['int',30],'p':['float',2],'metric':['callable','minkowski']}
grid=GridSearchCV(KNeighborsClassifier(),param_grid,refit=True,verbose=3,n_jobs=-1,scoring="f1_weighted")
grid.fit(x_train,y_train)

Fitting 5 folds for each of 128 candidates, totalling 640 fits

C:\Users\saran\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:425: FitFailedWarning:
600 fits failed out of a total of 640.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
320 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\saran\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 732, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\saran\anaconda3\Lib\site-packages\sklearn\base.py", line 1144, in wrapper
    estimator._validate_params()
  File "C:\Users\saran\anaconda3\Lib\site-packages\sklearn\base.py", line 637, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\saran\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'leaf_size' parameter of KNeighborsClassifier must be an int in the range [1, inf). Got 'int' instead.

--------------------------------------------------------------------------------
72 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\saran\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 732, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\saran\anaconda3\Lib\site-packages\sklearn\base.py", line 1144, in wrapper
    estimator._validate_params()
  File "C:\Users\saran\anaconda3\Lib\site-packages\sklearn\base.py", line 637, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\saran\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'metric' parameter of KNeighborsClassifier must be a str among {'l1', 'russellrao', 'hamming', 'chebyshev', 'cityblock', 'p', 'mahalanobis', 'dice', 'l2', 'yule', 'nan_euclidean', 'precomputed', 'jaccard', 'rogerstanimoto', 'sokalmichener', 'sokalsneath', 'infinity', 'sqeuclidean', 'cosine', 'haversine', 'seuclidean', 'correlation', 'pyfunc', 'euclidean', 'braycurtis', 'manhattan', 'minkowski', 'canberra'} or a callable. Got 'callable' instead.

--------------------------------------------------------------------------------
88 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\saran\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 732, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\saran\anaconda3\Lib\site-packages\sklearn\base.py", line 1144, in wrapper
    estimator._validate_params()
  File "C:\Users\saran\anaconda3\Lib\site-packages\sklearn\base.py", line 637, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\saran\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'metric' parameter of KNeighborsClassifier must be a str among {'minkowski', 'infinity', 'pyfunc', 'braycurtis', 'manhattan', 'russellrao', 'euclidean', 'yule', 'haversine', 'sqeuclidean', 'mahalanobis', 'sokalmichener', 'seuclidean', 'sokalsneath', 'l2', 'canberra', 'correlation', 'dice', 'cityblock', 'cosine', 'p', 'l1', 'chebyshev', 'jaccard', 'hamming', 'precomputed', 'nan_euclidean', 'rogerstanimoto'} or a callable. Got 'callable' instead.

--------------------------------------------------------------------------------
80 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\saran\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 732, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\saran\anaconda3\Lib\site-packages\sklearn\base.py", line 1144, in wrapper
    estimator._validate_params()
  File "C:\Users\saran\anaconda3\Lib\site-packages\sklearn\base.py", line 637, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\saran\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'n_neighbors' parameter of KNeighborsClassifier must be an int in the range [1, inf) or None. Got 'int' instead.

--------------------------------------------------------------------------------
40 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\saran\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 732, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\saran\anaconda3\Lib\site-packages\sklearn\base.py", line 1144, in wrapper
    estimator._validate_params()
  File "C:\Users\saran\anaconda3\Lib\site-packages\sklearn\base.py", line 637, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\saran\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'p' parameter of KNeighborsClassifier must be a float in the range (0.0, inf] or None. Got 'float' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Users\saran\anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:976: UserWarning: One or more of the test scores are non-finite: [       nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
 0.95904674 0.96276622        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan 0.95904674 0.96276622        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan 0.95904674 0.96276622
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
 0.95904674 0.96276622]
  warnings.warn(
C:\Users\saran\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:228: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)

GridSearchCV(estimator=KNeighborsClassifier(), n_jobs=-1,
             param_grid={'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
                         'leaf_size': ['int', 30],
                         'metric': ['callable', 'minkowski'],
                         'n_neighbors': ['int', 5], 'p': ['float', 2],
                         'weights': ['uniform', 'distance']},
             scoring='f1_weighted', verbose=3)

In [13]:
re=grid.cv_results_
grid_prediction=grid.predict(x_test)

In [14]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,grid_prediction)

In [15]:
from sklearn.metrics import classification_report
clf=classification_report(y_test,grid_prediction)

In [16]:
print("Report:\n",clf)

Report:
               precision    recall  f1-score   support

           0       0.89      1.00      0.94        51
           1       1.00      0.93      0.96        82

    accuracy                           0.95       133
   macro avg       0.95      0.96      0.95       133
weighted avg       0.96      0.95      0.96       133

In [17]:
print("confusion matrix:\n",cm)

confusion matrix:
 [[51  0]
 [ 6 76]]

In [18]:
from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_prediction,average='weighted')
print("The f1 macro value for best parameter {}:".format(grid.best_params_),f1_macro)

The f1 macro value for best parameter {'algorithm': 'auto', 'leaf_size': 30, 'metric': 'minkowski', 'n_neighbors': 5, 'p': 2, 'weights': 'distance'}: 0.955283779067923

In [19]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,grid.predict_proba(x_test)[:,1])

1.0

In [20]:
table=pd.DataFrame.from_dict(re)

In [21]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_algorithm,param_leaf_size,param_metric,param_n_neighbors,param_p,param_weights,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.003125,0.006251,0.000000,0.000000,auto,int,callable,int,float,uniform,"{'algorithm': 'auto', 'leaf_size': 'int', 'met...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
1,0.003125,0.006250,0.000000,0.000000,auto,int,callable,int,float,distance,"{'algorithm': 'auto', 'leaf_size': 'int', 'met...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
2,0.004783,0.005459,0.000000,0.000000,auto,int,callable,int,2,uniform,"{'algorithm': 'auto', 'leaf_size': 'int', 'met...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
3,0.002401,0.002335,0.000000,0.000000,auto,int,callable,int,2,distance,"{'algorithm': 'auto', 'leaf_size': 'int', 'met...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
4,0.004583,0.002389,0.000000,0.000000,auto,int,callable,5,float,uniform,"{'algorithm': 'auto', 'leaf_size': 'int', 'met...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123,0.000000,0.000000,0.000000,0.000000,brute,30,minkowski,int,2,distance,"{'algorithm': 'brute', 'leaf_size': 30, 'metri...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
124,0.000000,0.000000,0.000000,0.000000,brute,30,minkowski,5,float,uniform,"{'algorithm': 'brute', 'leaf_size': 30, 'metri...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
125,0.003125,0.006250,0.000000,0.000000,brute,30,minkowski,5,float,distance,"{'algorithm': 'brute', 'leaf_size': 30, 'metri...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
126,0.003125,0.006251,0.075004,0.056252,brute,30,minkowski,5,2,uniform,"{'algorithm': 'brute', 'leaf_size': 30, 'metri...",0.963284,0.962636,0.925524,0.981217,0.962573,0.959047,0.018213,5
127,0.009376,0.007655,0.046877,0.000001,brute,30,minkowski,5,2,distance,"{'algorithm': 'brute', 'leaf_size': 30, 'metri...",0.963284,0.981233,0.925524,0.981217,0.962573,0.962766,0.020341,1

In [22]:
age_input=float(input("age:"))
bp_input=float(input("bp:"))
al_input=int(input("al:"))
su_input=int(input("su:"))
bgr_input=float(input("bgr:"))
bu_input=float(input("bu:"))
sc_input=float(input("sc:"))
sod_input=float(input("sod:"))
pot_input=float(input("pot:"))
hrmo_input=float(input("hrmo:"))
pcv_input=int(input("pcv:"))
wc_input=float(input("wc:"))
rc_input=float(input("rc:"))
sg_b_input=int(input("sg_b:"))
sg_e_input=int(input("sg_e:"))
sg_d_input=int(input("sg_d:"))
sg_c_input=int(input("sg_c:"))
rbc_normal_input=int(input("rbc_normal:"))
pc_normal_input=int(input("pc_normal:"))
pcc_present_input=int(input("pcc_present:"))
ba_present_input=int(input("ba_present:"))
htn_yes_input=int(input("htn_yes:"))
dm_yes_input=int(input("dm_yes:"))
cad_yes_input=int(input("cad_yes:"))
appet_yes__input=int(input("appet_yes:"))
pe_yes_input=int(input("pe_yes:"))
ane_yes_input=int(input("ane_yes:"))

age:3.00
bp:70
al:3
su:0
bgr:130
bu:456
sc:134.8
sod:34
pot:23
hrmo:56
pcv:87
wc:8000
rc:578
sg_b:0
sg_e:1
sg_d:1
sg_c:1
rbc_normal:1
pc_normal:1
pcc_present:0
ba_present:0
htn_yes:0
dm_yes:0
cad_yes:0
appet_yes:0
pe_yes:0
ane_yes:0

In [23]:
future_predictions=grid.predict([[age_input,bp_input,al_input,su_input,bgr_input,bu_input,sc_input,sod_input,pot_input,hrmo_input,pcv_input,wc_input,rc_input,sg_b_input,sg_e_input,sg_c_input,sg_d_input,rbc_normal_input,pc_normal_input,pcc_present_input,ba_present_input,htn_yes_input,dm_yes_input,cad_yes_input,appet_yes__input,pe_yes_input,ane_yes_input]])
print("future predictions:{}".format(future_predictions))

future predictions:[1]