In [25]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [26]:
dataset=pd.read_csv("CKD.csv")

In [27]:
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3,0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2,0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1,0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1,0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0,0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0,0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0,2,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3,0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0,0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0,0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [28]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [29]:
dataset=dataset.astype(int)

In [30]:
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2,76,3,0,148,57,3,137,4,12,...,0,0,0,0,0,0,1,1,0,1
1,3,76,2,0,148,22,0,137,4,10,...,1,0,0,0,0,0,1,0,0,1
2,4,76,1,0,99,23,0,138,4,12,...,1,0,0,0,0,0,1,0,0,1
3,5,76,1,0,148,16,0,138,3,8,...,1,0,0,0,0,0,1,0,1,1
4,5,50,0,0,148,25,0,137,4,11,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51,70,0,0,219,36,1,139,3,12,...,1,0,0,0,0,0,1,0,0,1
395,51,70,0,2,220,68,2,137,4,8,...,1,0,0,1,1,0,1,0,1,1
396,51,70,3,0,110,115,6,134,2,9,...,1,0,0,1,1,0,0,0,0,1
397,51,90,0,0,207,80,6,142,5,8,...,1,0,0,1,1,0,1,0,1,1
398,51,80,0,0,100,49,1,140,5,16,...,1,0,0,0,0,0,1,0,0,0

In [31]:
dataset["classification_yes"].value_counts()

classification_yes
1    249
0    150
Name: count, dtype: int64

In [32]:
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [33]:
independent=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', ]]

In [34]:
independent

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,rbc_normal,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes
0,2,76,3,0,148,57,3,137,4,12,...,1,0,0,0,0,0,0,1,1,0
1,3,76,2,0,148,22,0,137,4,10,...,1,1,0,0,0,0,0,1,0,0
2,4,76,1,0,99,23,0,138,4,12,...,1,1,0,0,0,0,0,1,0,0
3,5,76,1,0,148,16,0,138,3,8,...,1,1,0,0,0,0,0,1,0,1
4,5,50,0,0,148,25,0,137,4,11,...,1,1,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51,70,0,0,219,36,1,139,3,12,...,1,1,0,0,0,0,0,1,0,0
395,51,70,0,2,220,68,2,137,4,8,...,1,1,0,0,1,1,0,1,0,1
396,51,70,3,0,110,115,6,134,2,9,...,1,1,0,0,1,1,0,0,0,0
397,51,90,0,0,207,80,6,142,5,8,...,1,1,0,0,1,1,0,1,0,1
398,51,80,0,0,100,49,1,140,5,16,...,1,1,0,0,0,0,0,1,0,0

In [35]:
dependent=dataset[['classification_yes']]

In [36]:
dependent

     classification_yes
0                     1
1                     1
2                     1
3                     1
4                     1
..                  ...
394                   1
395                   1
396                   1
397                   1
398                   0

[399 rows x 1 columns]

In [37]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independent,dependent,test_size=1/3,random_state=0)

In [38]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [39]:
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
param_grid={"kernel":["sigmoid","poly","linear","rbf"],"C":[10,100,1000,2000,3000]}
grid=GridSearchCV(SVC(probability=True),param_grid,refit=True,verbose=3,n_jobs=-1,scoring='f1_weighted')
grid.fit(x_train,y_train)

Fitting 5 folds for each of 20 candidates, totalling 100 fits

C:\Users\saran\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GridSearchCV(estimator=SVC(probability=True), n_jobs=-1,
             param_grid={'C': [10, 100, 1000, 2000, 3000],
                         'kernel': ['sigmoid', 'poly', 'linear', 'rbf']},
             scoring='f1_weighted', verbose=3)

In [40]:
re=grid.cv_results_
grid_predictions=grid.predict(x_test)

In [41]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,grid_predictions)

In [42]:
from sklearn.metrics import classification_report
clf=classification_report(y_test,grid_predictions)

In [43]:
print("The Report:\n",clf)

The Report:
               precision    recall  f1-score   support

           0       0.96      1.00      0.98        51
           1       1.00      0.98      0.99        82

    accuracy                           0.98       133
   macro avg       0.98      0.99      0.98       133
weighted avg       0.99      0.98      0.99       133

In [44]:
print("Confusion Matrix:\n",cm)

Confusion Matrix:
 [[51  0]
 [ 2 80]]

In [45]:
from sklearn.metrics import  f1_score
f1_macro=f1_score(y_test,grid_predictions,average="weighted")
print("The f1 macro value for best parameter:{}".format(grid.best_params_),f1_macro)

The f1 macro value for best parameter:{'C': 10, 'kernel': 'sigmoid'} 0.9850141736106648

In [46]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,grid.predict_proba(x_test)[:,1])

1.0

In [47]:
table=pd.DataFrame.from_dict(re)

In [48]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.018750,6.249571e-03,0.028128,0.006249,10,sigmoid,"{'C': 10, 'kernel': 'sigmoid'}",0.981569,0.981233,1.000000,0.981031,1.000000,0.988767,0.009174,1
1,0.025002,7.656272e-03,0.018751,0.006249,10,poly,"{'C': 10, 'kernel': 'poly'}",1.000000,0.961755,1.000000,0.981031,0.981217,0.984801,0.014284,3
2,0.012501,6.250310e-03,0.025001,0.007654,10,linear,"{'C': 10, 'kernel': 'linear'}",0.963284,0.943699,0.962573,0.962264,0.981217,0.962607,0.011869,16
3,0.012502,6.250835e-03,0.025001,0.007656,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.963284,0.962264,1.000000,1.000000,1.000000,0.985110,0.018240,2
4,0.018751,6.249404e-03,0.021876,0.007655,100,sigmoid,"{'C': 100, 'kernel': 'sigmoid'}",0.981569,0.943699,0.944023,0.981031,1.000000,0.970065,0.022459,12
5,0.025002,7.654325e-03,0.021877,0.007654,100,poly,"{'C': 100, 'kernel': 'poly'}",0.963284,0.981014,1.000000,0.981031,0.981217,0.981309,0.011614,11
6,0.015626,9.488940e-07,0.028126,0.011694,100,linear,"{'C': 100, 'kernel': 'linear'}",0.963284,0.943699,0.962573,0.962264,0.981217,0.962607,0.011869,16
7,0.012500,6.249809e-03,0.018752,0.006251,100,rbf,"{'C': 100, 'kernel': 'rbf'}",0.963284,0.962264,1.000000,0.981031,1.000000,0.981316,0.016652,7
8,0.015626,2.365035e-06,0.018751,0.006250,1000,sigmoid,"{'C': 1000, 'kernel': 'sigmoid'}",0.981569,0.943699,0.962573,0.981031,0.981217,0.970018,0.015021,13
9,0.018751,6.250119e-03,0.025003,0.007652,1000,poly,"{'C': 1000, 'kernel': 'poly'}",0.963284,0.981014,0.981217,1.000000,0.981217,0.981346,0.011613,4
10,0.009377,7.656369e-03,0.021875,0.007658,1000,linear,"{'C': 1000, 'kernel': 'linear'}",0.963284,0.943699,0.962573,0.962264,0.981217,0.962607,0.011869,16
11,0.018751,6.249881e-03,0.021876,0.007656,1000,rbf,"{'C': 1000, 'kernel': 'rbf'}",0.963284,0.962264,1.000000,0.981031,1.000000,0.981316,0.016652,7
12,0.012500,6.250096e-03,0.021876,0.007655,2000,sigmoid,"{'C': 2000, 'kernel': 'sigmoid'}",0.981569,0.943699,0.962573,0.981031,0.981217,0.970018,0.015021,13
13,0.024999,7.655103e-03,0.021878,0.007654,2000,poly,"{'C': 2000, 'kernel': 'poly'}",0.963284,0.981014,0.981217,1.000000,0.981217,0.981346,0.011613,4
14,0.015623,4.044411e-06,0.021881,0.007655,2000,linear,"{'C': 2000, 'kernel': 'linear'}",0.963284,0.943699,0.962573,0.962264,0.981217,0.962607,0.011869,16
15,0.015624,4.252682e-06,0.025002,0.007654,2000,rbf,"{'C': 2000, 'kernel': 'rbf'}",0.963284,0.962264,1.000000,0.981031,1.000000,0.981316,0.016652,7
16,0.012499,6.249285e-03,0.021878,0.007653,3000,sigmoid,"{'C': 3000, 'kernel': 'sigmoid'}",0.981569,0.943699,0.962573,0.981031,0.981217,0.970018,0.015021,13
17,0.025002,7.655785e-03,0.021875,0.007656,3000,poly,"{'C': 3000, 'kernel': 'poly'}",0.963284,0.981014,0.981217,1.000000,0.981217,0.981346,0.011613,4
18,0.012501,6.250429e-03,0.021876,0.007656,3000,linear,"{'C': 3000, 'kernel': 'linear'}",0.963284,0.943699,0.962573,0.962264,0.981217,0.962607,0.011869,16
19,0.012500,6.250072e-03,0.025002,0.007655,3000,rbf,"{'C': 3000, 'kernel': 'rbf'}",0.963284,0.962264,1.000000,0.981031,1.000000,0.981316,0.016652,7

In [49]:
age_input=float(input("age:"))
bp_input=float(input("bp:"))
al_input=int(input("al:"))
su_input=int(input("su:"))
bgr_input=float(input("bgr:"))
bu_input=float(input("bu:"))
sc_input=float(input("sc:"))
sod_input=float(input("sod:"))
pot_input=float(input("pot:"))
hrmo_input=float(input("hrmo:"))
pcv_input=int(input("pcv:"))
wc_input=float(input("wc:"))
rc_input=float(input("rc:"))
sg_b_input=int(input("sg_b:"))
sg_e_input=int(input("sg_e:"))
sg_d_input=int(input("sg_d:"))
sg_c_input=int(input("sg_c:"))
rbc_normal_input=int(input("rbc_normal:"))
pc_normal_input=int(input("pc_normal:"))
pcc_present_input=int(input("pcc_present:"))
ba_present_input=int(input("ba_present:"))
htn_yes_input=int(input("htn_yes:"))
dm_yes_input=int(input("dm_yes:"))
cad_yes_input=int(input("cad_yes:"))
appet_yes__input=int(input("appet_yes:"))
pe_yes_input=int(input("pe_yes:"))
ane_yes_input=int(input("ane_yes:"))

age:3.00
bp:3.00
al:70
su:3
bgr:0
bu:130
sc:456
sod:134.8
pot:34
hrmo:23
pcv:56
wc:87
rc:8000
sg_b:578
sg_e:0
sg_d:1
sg_c:1
rbc_normal:1
pc_normal:1
pcc_present:0
ba_present:0
htn_yes:0
dm_yes:0
cad_yes:0
appet_yes:0
pe_yes:0
ane_yes:0

In [50]:
future_predictions=grid.predict([[age_input,bp_input,al_input,su_input,bgr_input,bu_input,sc_input,sod_input,pot_input,hrmo_input,pcv_input,wc_input,rc_input,sg_b_input,sg_e_input,sg_c_input,sg_d_input,rbc_normal_input,pc_normal_input,pcc_present_input,ba_present_input,htn_yes_input,dm_yes_input,cad_yes_input,appet_yes__input,pe_yes_input,ane_yes_input]])
print("future predictions:{}".format(future_predictions))

future predictions:[0]